# NOTE: 추후에 각각 책의 라벨이 추가될 때 마다 확인 후 추가 필요

version: 1
labels:
  - label: "2024"
    files:
      - "2024/*"
  - label: "The Psychology of Computer Programming"
    files:
      - "2024/ThePsychologyOfComputerProgramming/*"
  - label: "Patterns of Enterprise Application Architecture"
    files:
      - "2024/PatternsOfEnterpriseApplicationArchitecture/*"
