name: "On Pull Request Opened"

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  comment-for-filling-others-like-projects-milestone-development-etc:
    runs-on: ubuntu-latest
    steps:
      - uses: JoseThen/comment-pr@v1.2.0
        with:
          comment: "우측에 있는 `Projects`, `Milestone`, `Development`를 확인 후 할당 해주세요~! :bow:"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
